### ISSUE TITLE
首先，先点个赞，终于找到可用的了。然后，是否可以添加个快捷键，按Esc退出放大

### ISSUE THREAD

**Issue by wuzeqingit** [theyangfan/WordPictureViewer#2]
首先，先点个赞，终于找到可用的了。然后，是否可以添加个快捷键，按Esc退出放大

**Comment by theyangfan** [comment]
你好，最新版中支持了Esc退出功能，欢迎试用 [1.0.2 (2023-04-10)](https://github.com/theyangfan/WordPictureViewer/releases/tag/1.0.2) ！
