### ISSUE TITLE
调整可缩小的倍数

### ISSUE THREAD

**Issue by in-your-dreams** [theyangfan/WordPictureViewer#3]
目前我看作者的代码好像是：当滚轮向上滚动（即 e.Delta > 0）时，代码会增加 _scaleStep 的值，从而增加 _scale 的值，实现放大。而当滚轮向下滚动时，代码会减少 _scaleStep 的值，但有一个条件限制 _scale + _scaleStep 必须大于或等于 100，这意味着 _scale 的值不能小于 100，因此不能实现缩小。

我想可不可以修改一下，缩小最小可以在50%或者70%左右，毕竟有的时候100%的放大也是很大的

if(e.Delta > 0) // zoom in
{
    _scaleStep = Math.Abs(_scaleStep); // Ensure _scaleStep is positive
    _scale += _scaleStep;
}
else // zoom out
{
    _scaleStep = -Math.Abs(_scaleStep); // Ensure _scaleStep is negative
    _scale += _scaleStep;
}
    
// Ensure _scale doesn't go below a certain minimum (e.g., 50%)
_scale = Math.Max(_scale, 50);

**Comment by theyangfan** [comment]
你好，感谢你的提议。已将最新版本中的最小缩放率调整为50% -> [v1.0.3](https://github.com/theyangfan/WordPictureViewer/releases/tag/1.0.3)
